#!/usr/bin/python3
def raise_exception_msg(message=""):
    try:
        almah = 1
        print(alma)
    except NameError:
        print('Veriable not defined')
